name: Deploy Webpage

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apache and Java Runtime Environment (JRE)
        run: |
             sudo apt-get update && sudo apt-get install -y apache2
             sudo apt-get install default-jre -y

      - name: Enable Firewall
        run: sudo ufw enable

      - name: Allow traffic on port 80
        run: sudo ufw allow 80/tcp

      - name: Copy files to Apache document root
        run: sudo cp index.html /var/www/html/

      - name: Restart Apache
        run: sudo systemctl reload apache2

      - name: Display Server IP
        run: sudo curl ifconfig.me

      - name: Display localhost
        run: sudo curl localhost

