name: Deploy Webpage

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apache
        run: |
             sudo apt-get update && sudo apt-get install -y apache2
             sudo apt-get install default-jre -y
             
      - name: Copy files to Apache document root
        run: sudo cp  ./index.html /var/www/html/

      - name: Restart Apache
        run: |
           sudo service apache2 restart
           sudo curl ifconfig.me
           sudo curl localhost
          
