name: Deploy Webpage
on:
  push:
    branches:
      - main  # Adjust this according to your branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing Docker Engine 
        run: sudo apt update && sudo apt install -y docker.io
      - name:  start & enable service 
        run: sudo systemctl start docker && sudo systemctl enable docker
      - name: provide permission to the user 
        run: sudo chown $USER:$USER /var/run/docker.sock
      - name: Building The Docker File
        run: docker build -t hotstar_test .
      - name: Running the container of the image
        run: docker run -dit -p 8080:8080 hotstar_test  && docker ps
        
