name: Deploy Webpage
on:
  push:
    branches:
      - main  # Adjust this according to your branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing Webserver #(Apache) 
        run: sudo apt-get update && sudo apt-get install -y apache2
      - name:  start & enable service 
        run: sudo systemctl start apache2 && sudo systemctl enable apache2
