name: Docker Workflow

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo chown $USER:$USER /var/run/docker.sock

      - name: Build Docker image
        run: docker build -t my-web-app .

      - name: Run Docker container
        run: docker run -d -p 8080:80 my-web-app
